### ISSUE TITLE
installazione docker di MM su VPS centOS

### ISSUE THREAD

**Issue by giodegas** [iorestoacasa-work/iorestoacasa.work#68]
Ho seguito tutte le istruzioni pubblicate installando su una VPS con centOS, anche se nella generazione dei certificati la procedura mi appare diversa. G DG, Quando uso `certbot` mi genera file diversi da quelli indicati nelle istruzioni, ma credo di aver individuato correttamente i file` .pem` del certificato e della chiave privata; 

    certbot --config-dir .certbot/config --work-dir .certbot/work  --logs-dir .certbot/logs certonly -d <mio dominio> --standalone

li ho salvati nella cartella `certs` con i nomi indicati nelle istruzioni.

    # ls certs
    fullchain.pem  privkey.pem

Il problema che si presenta è che non espone mai il servizio web su porta 80.
Se do il comando:

    docker logs mm

mi da:

    - process.env.DEBUG: undefined
    - config.mediasoup.logLevel: undefined
    - config.mediasoup.logTags: undefined
    (node:6) UnhandledPromiseRejectionWarning: Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:135:17)
    at Server (_tls_wrap.js:873:27)
    at Server (https.js:62:14)
    at Server._init (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:62:10)
    at new Server (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:25:10)
    at Function.create (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:30:12)
    at Object.create [as createServer] (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:286:27)
    at runHttpsServer (/opt/multiparty-meeting/server/server.js:436:23)
    at run (/opt/multiparty-meeting/server/server.js:141:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
    (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tapionx** [comment]
@giodegas hai più risolto il problema?

**Comment by giodegas** [comment]
No

**Comment by tapionx** [comment]
ho provato ad acquistare una VPS con CentOS 8 e sono riuscito ad installare MM seguendo la procedura.
L'errore che hai pubblicato sembra proprio relativo ad un certificato che ha un formato sbagliato.
Puoi riprovare con dei certificati self-signed e vedere se cambia qualcosa?
